### ISSUE TITLE
Dataloader for CUB

### ISSUE THREAD

**Issue by LoveMiki** [zjgans/dcan#1]
How can your CUB dataloader work for the CUB dataset provided on the Readme page?

**Comment by zjgans** [comment]
Sorry, there seems to be a problem here, you can visit "https://github.com/icoz69/DeepEMD/blob/master/datasets/download_cub.sh", where you can get the download link of CUB.

**Comment by LoveMiki** [comment]
How to run your code? I noticed that I need to first run the setup.py file to build the environment for ddf. But when I run the file, it threw an error "no commands supplied".
Could you provide more details for implementing your code?

**Comment by LoveMiki** [comment]
How to run your code? I tried to implement the command "bash scripts/train/miniimagenet_5w5s.sh", but it threw an error: ImportError: cannot import name 'ddf_mul_ext' from partially initialized module 'ddf' (most likely due to a circular import) (/home/smslab/PycharmProjects/dcan-master/ddf/__init__.py).
How to fix the error?

**Comment by LoveMiki** [comment]
> How to run your code? I tried to implement the command "bash scripts/train/miniimagenet_5w5s.sh", but it threw an error: ImportError: cannot import name 'ddf_mul_ext' from partially initialized module 'ddf' (most likely due to a circular import) (/home/smslab/PycharmProjects/dcan-master/ddf/**init**.py). How to fix the error?

I have figured out the problem.

**Comment by zjgans** [comment]
I did not encounter this problem, you can first run /ddf/setup.py: python setup.py develop. The environment is python=3.8, pytorch=1.8. I hope this suggestion is useful to you. If you still can't solve it, you can seek help from relevant peers around you.

**Comment by LoveMiki** [comment]
> I did not encounter this problem, you can first run /ddf/setup.py: python setup.py develop. The environment is python=3.8, pytorch=1.8. I hope this suggestion is useful to you. If you still can't solve it, you can seek help from relevant peers around you.

Thank you for your prompt reply.
Could you explain the purpose of generating img2, img3, and img4 in aux_dataloader.py? It seems that you are enlarging the image pool of dataloader for later data sampling. And in the train.py, every time you only choose data_aux[0] for training. Why do not use data_aux[1] or data_aux[2] or data_aux[3]?
